### PR TITLE
Fix #285: Add a "contents" property to the "file" object

### LINKED ISSUE #285: Add a "contents" property to the "file" object
Optional. Contains a Base-64-encoded representation of the file contents.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by michaelcfanning** [comment]
LGTM. We need a corresponding change in SARIF SDK to update schema. We need to republish the SARIF JSON scheme to schemastore

**Review by michaelcfanning — APPROVED** [review]
:shipit:

**Comment by ghost** [comment]
Yes, I will file the work item.

---
In reply to: [324456707](https://github.com/sarif-standard/sarif-spec/pull/287#issuecomment-324456707) [](ancestors = 324456707)

**Comment by ghost** [comment]
Filed
- Github [Issue #594](https://github.com/Microsoft/sarif-sdk/issues/594), "Support file.contents"
- VSTS [User Story 13581](https://wdginformationsecurity.visualstudio.com/WDGIS/Security%20Support/_workitems/edit/13581), "sarif-sdk supports file.contents"

---
In reply to: [324458489](https://github.com/sarif-standard/sarif-spec/pull/287#issuecomment-324458489) [](ancestors = 324458489,324456707)

**Pull request merged**
