### PR TITLE
Fix #91: Should runInfo have a date/time-valued runDate property?

### LINKED ISSUE #91: Should runInfo have a date/time-valued runDate property?

### PR DESCRIPTION
**Pull request by ghost**
@michaelcfanning

### CODE REVIEW

**Comment by michaelcfanning** [comment]
Will anyone care to specify a start vs. end time?

**Comment by ghost** [comment]
Sure, sounds good.

**Comment by michaelcfanning** [comment]
Forgive me for making this comment, but your original name was runDateTime. Now that we have a start and end value, you have eliminated 'Date' in preference of runStartTime and runEndTime. Did you do this from a sense that the name would get too long otherwise? If we don't have a fully descriptive member name, perhaps we should head the other way and prefer 'runStart' or 'runEnd'? 

runStartTimestamp and runEndTimestamp also available for consideration.

**Comment by ghost** [comment]
It was a purely aesthetic decision. The resulting name was too long, and I stepped back and asked myself, "is anybody really going to be confused and think that this thing can't include a date?". And I answered "no". Precedents: file{creation,modification,access}time, various properties in .NET classes.

**Comment by ghost** [comment]
I'm going to merge this. Feel free to press me on this _post hoc_, but I'll take some convincing.

**Comment by michaelcfanning** [comment]
I'm convinced.

**Pull request merged**
