### PR TITLE
Propose eliminating 'location' as a prefix of 'locationKind' as we wi…

### PR DESCRIPTION
**Pull request by michaelcfanning**
…ll shortly introduce a result kind without a prefix and we should be consistent.

@nguerrera @lgolding 

Note that I can't provide an update to the compiled HTML until we accept all outstanding changes.

### CODE REVIEW

**Comment by michaelcfanning** [comment]
#45

**Comment by ghost** [comment]
My name is Larry Golding and I approve this change. :+1:

**Comment by michaelcfanning** [comment]
let it be so. updated HTML using build script before merging.

**Comment by nguerrera** [comment]
:+1:

**Pull request merged**
